### ISSUE TITLE
Using alongside Flux, only works like 50% of the time?

### ISSUE THREAD

**Issue by ghost** [Inzaniak/comfyui-ranbooru#6]
Other 50% it outputs this error:
!!! Exception during processing !!! 'post'
Traceback (most recent call last):
  File "C:\Users\chray\OneDrive\Documents\ComfyUI\execution.py", line 313, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chray\OneDrive\Documents\ComfyUI\execution.py", line 188, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chray\OneDrive\Documents\ComfyUI\execution.py", line 165, in map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\chray\OneDrive\Documents\ComfyUI\execution.py", line 154, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chray\OneDrive\Documents\ComfyUI\custom_nodes\comfyui-ranbooru\ranbooru.py", line 293, in ranbooru
    random_post = data['post'][random.randint(0,len(data['post'])-1)]
                  ~~~~^^^^^^^^
KeyError: 'post'


The only thing I'm changing is tags, some fail more than others, like "lovely_labrynth_of_the_silver_castle" only works 1 in 10 generations. while something like 1girl harpy has 50% failrate on gelbooru.

**Comment by XdivineExp** [comment]
This often happens when there isn't enough content on the booru to satisfy the 'max pages' you have selected on the node. So like if you choose something like '1girl, cat ears', you'll probably have no problems even at 100 max pages, but when you start getting into more niche tags that have fewer pages of results then it'll start throwing errors constantly.

So what I would suggest is if you try a set of tokens and you're seeing errors a lot, run those same tokens through gelbooru and see how many pages of results there are then adjust your max pages accordingly. Unfortunately, even going a few pages under the number of pages on booru sites will occasionally throw me errors still, but it's at least drastically reduced. So if there are 15 pages, maybe try 10, if there are 30, try 20 or 25, that kinda thing.
